// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDndS7OlXrx2nk8Y53w18mV770rK5ZfpGg',
    appId: '1:249754258882:web:d07aed2bd8d9d5cb34da5b',
    messagingSenderId: '249754258882',
    projectId: 'npdo-flutter',
    authDomain: 'npdo-flutter.firebaseapp.com',
    storageBucket: 'npdo-flutter.appspot.com',
    measurementId: 'G-TRBV1R8RMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp8HPDscbl4LTZu06L1w7jVKIm2R8bDIo',
    appId: '1:249754258882:android:9dbfd74da8aafd6634da5b',
    messagingSenderId: '249754258882',
    projectId: 'npdo-flutter',
    storageBucket: 'npdo-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAF3vewfjWdVs-f6Hbo8MDY50Bg9pzC5w',
    appId: '1:249754258882:ios:a3a1e6115ac793bf34da5b',
    messagingSenderId: '249754258882',
    projectId: 'npdo-flutter',
    storageBucket: 'npdo-flutter.appspot.com',
    iosClientId: '249754258882-nsfdqp1gul5lsm1iemec7n8nv4bka4gi.apps.googleusercontent.com',
    iosBundleId: 'com.example.npdoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAF3vewfjWdVs-f6Hbo8MDY50Bg9pzC5w',
    appId: '1:249754258882:ios:a3a1e6115ac793bf34da5b',
    messagingSenderId: '249754258882',
    projectId: 'npdo-flutter',
    storageBucket: 'npdo-flutter.appspot.com',
    iosClientId: '249754258882-nsfdqp1gul5lsm1iemec7n8nv4bka4gi.apps.googleusercontent.com',
    iosBundleId: 'com.example.npdoFlutter',
  );
}
